# Generated by Django 5.0 on 2024-01-05 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='categorie',
        ),
    ]
